config/routes.rb
Rails.application.routes.draw do

  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  # get 'books/edit'

  root to: 'homes#top'
  resources :books
  patch 'books/:id' => 'books#update', as: 'update_book'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
       flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to  books_path
  end

  private
    # ストロングパラメータ
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>

  <h1>Editing Book</h1>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>

  <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

    <div class="field">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label for="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class="action">
        <%= f.submit 'Update Book' %>
    </div>

    <%= link_to "Show", book_path(@book.id) %>
     |
    <id=books><a href="/books">Back</a></id>

  <% end %>

</body>

app/views/books/index.html.erb
<body>
  <div class="Books">
    <h1>Books</h1>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to 'Show', book_path(book) %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <h2>New book</h2>

  <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @book do |f| %>

    <div class="field">
      <label for="book_title">Title</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label for="book_body">Body</label>
      <%= f.text_area :body %>
    </div>

    <div class="action">
        <%= f.submit 'Create Book' %>
    </div>

  <% end %>

</body>

app/views/books/new.html.erb
<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Creat Book' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:notice]  %>

<p>
    <strong>Title</strong>
    <%= @book.title %>
</p>

<p>
    <strong>Body</strong>
    <%= @book.body %>
</p>


<%= link_to "Edit", edit_book_path(@book.id) %>
  |
<id=books><a href="/books">Back</a></id>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="otXUPUhjSoxc+KtCkdiIhTNle05Bc3Ap1CBoLlMVWEKRytrqTHcrwWFgEbpehNILusChiruuaNlL36rcqtVC0Q==" />

    <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload" />
    <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
  </head>

  <body>
    <h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookers
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body

  .notification
   - flash.each do |key, value|
    = content_tag :div, value, class: key

    = yield